---
- hosts: all
  become: true
  gather_facts: False
  tasks:
  - name: Load in vars
    include_vars:
      file: ../Defaults/main.yml

  - name: Install apache2 packages
    apt:
     name: "{{ item }}"
     state: installed
     update_cache: yes
    with_items: "{{ ubuntu_1604_apache2_pkgs }}"

  - name: Copy the apache2 conf file
    template:
      src: ../Templates/apache2.conf.j2
      dest: /etc/apache2/apache2.conf
      mode: 0644

  - name: Copy the data dog test site conf file
    template:
      src: ../Templates/001-ddTest.conf.j2
      dest: /etc/apache2/sites-available/001-ddTest.conf
      mode: 0644

  - name: Create a directory for dd test
    file:
      path: /var/www/ddTest/public_html
      state: directory
      mode: 0755

  - name: restart apache to make sure all is in order
    service:
      name: apache2
      state: restarted